version: '3'
services:
  app:
    image: nocrastinate
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # - MONGODB_USERNAME
      # - MONGODB_PASSWORD
      # - MONGODB_REMOTE
      - MONGODB_DATABASE=nocrastinate
      - MONGODB_CONNECTION_STRING=mongodb://mongo/nocrastinate
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./src:/app/src
  mongo:
    image: mongo
    ports:
      - 27017:27017
